import React from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import Layout from 'components/Layout/Index';

const AdsContainer = dynamic(() => import('containers/Adsense'));

const Page = () => {
    return (
        <>
            <Head>
                <title>Casual Result | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
                <script type='text/javascript' src='//imasdk.googleapis.com/js/sdkloader/ima3.js' />
                <script type='text/javascript' src='ads.js' />
            </Head>
            <Layout backgoundColor='#fff'>
                <AdsContainer />
            </Layout>
        </>
    );
};

export default Page;
