import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const InboxContainer = dynamic(() => import('containers/Inbox'));

const Page = () => {
    return (
        <>
            <Head>
                <title>Inbox | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <InboxContainer />
        </>
    );
};

export default Page;
