import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Layout from 'components/Layout/Index';

const GameContainer = dynamic(() => import('containers/Game'), { ssr: false });

const Page = () => {
    return (
        <>
            <Head>
                <title>Game | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout isTab>
                <GameContainer playerImg1='' playerImg2='' playerImg3='' totalPlayer={0} />
            </Layout>
        </>
    );
};

export default Page;
