import Layout from 'components/Layout/Index';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import React from 'react';

const ProfileContainer = dynamic(() => import('containers/Profile'));

const Page = () => {
    return (
        <>
            <Head>
                <title>Home | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Layout backgoundColor='#fff'>
                <ProfileContainer />
            </Layout>
        </>
    );
};

export default Page;
