import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const MissionContainer = dynamic(() => import('containers/Mission'), { ssr: false });

const Page = () => {
    return (
        <>
            <Head>
                <title>Mission | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <MissionContainer />
        </>
    );
};

export default Page;
