import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const HistoryContainer = dynamic(() => import('containers/History'));
const Page = () => {
    return (
        <>
            <Head>
                <title>History | Prize Play</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <HistoryContainer />
        </>
    );
};

export default Page;
